### PR TITLE
Correct Linux version constraint to 4.10.

### PR DESCRIPTION
**Pull request by kwilczynski**
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>

### CODE REVIEW

**Comment by netanelbelgazal** [comment]
You are right, we have a typo here.
It should have been 4.10.
I'll push a fix for that soon.

The typo's only effect is that the driver in kernel 4.10 will use it's own atomic variable to unmask interrupts instead of using napi_complete_done() return value.
So there isn't any thread/bug here.

**Comment by kwilczynski** [comment]
@netanelbelgazal I can push update to this Pull Request, would that be fine?

**Comment by kwilczynski** [comment]
@netanelbelgazal Done. It's 4.10 now.

**Comment by kwilczynski** [comment]
@netanelbelgazal I am going to close this one, since 1.2.0 was made available (thank you!) and this is no longer an issue.

**Pull request closed without merging**
